### ISSUE TITLE
Other TODOs

### ISSUE THREAD

**Issue by AndMJ** [ptv1p3r/ptm_frontend#31]
### TODO: 
- ~~atualizar $_SESSION quando aconteçer CRUD groups, securitys, etc, para garantir segurança(permissions)~~
- **~~encriptar passwords no create e edit de Users, usar: hash('sha256', $pass)~~

<br>

- ALL pages:
- [x] translate all
- [x] hide table "active" col & rearrange respective button
- [x] FIX modals to have selectize.js & active field to be a switch instead of checkbox
- [x] validar permissions em functions no controller
- [x] revisao de tables (ver se falta algum campo do tipo datas de criaçao ...)

<br>

- Page trees:
- [x] FIX table to show tree id
- [x] filter map to show active / inactive (map overlays for active and inactive)

<br>

- Page settings:
- [x] FIX "editar perfil" form genero label

<br>

- Page messages & all_messages:
- [x] FIX all_messages compose message button size
- ~~change actions to be shown only if any message in table~~

<br>

### Pages translated:
- [x] messages
- [x] all messages

<br>

- [x] dashboard
- [x] groups
- [x] users
- [x] securitys

<br>

- [x] trees dashboard
- [x] trees
- [x] user trees 
- [x] tree type 
- [x] tree images 
- [x] tree interventions

<br>

- [x] transaction
- [x] transaction types
- [x] transaction methods

<br>

- [x] settings

** importado de outro issue
