### ISSUE TITLE
Menu Trees (cont.)

### ISSUE THREAD

**Issue by AndMJ** [ptv1p3r/ptm_frontend#43]
continuação do menu trees

**Comment by AndMJ** [comment]
### OFF-TOPIC:
- [x] tabelas com dataTables API & active/inactive filters
- [x] trocar logotipo do backoffice
- [x] implementar loaders nas açoes do CRUD em todas as views
- [ ] **encriptar passwords no create e edit de Users, usar: hash('sha256', $pass)

### TODO:
- [x] CRUD
  - [ ] atribuir images a trees  
    - https://plugins.krajee.com/file-preview-management-demo
    - https://jsfiddle.net/pwe1uyhc/
  - [x] atribuir trees a users
  - [x] tree interventions
  - [x] tree types
  - [x] trees
- [x] MAPA
  - [x] mostrar arvores vindas da API
  - [ ] cards com info das arvores


** importado de outro issue
